In [1]:
pip install mediapipe==0.10.9

In [ ]:
import cv2
import mediapipe as mp
import numpy as np
from google.colab.patches import cv2_imshow

def VirtualCoorMediaPipe(image):
    mp_pose = mp.solutions.pose
    pose = mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5)

    excluded_points = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 13, 14, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
    landmarks_list = []

    if image is None:
        print("Error: Image not found or cannot be loaded.")
        return None

    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    result = pose.process(image_rgb)

    if result.pose_landmarks:
        for idx, landmark in enumerate(result.pose_landmarks.landmark):
            x = int(landmark.x * image.shape[1])
            y = int(landmark.y * image.shape[0])
            if idx not in excluded_points:
                print(f"point {idx}: coordinates ({x:.1f}, {y:.1f})")
                landmarks_list.append([x, y, 1])  # Adding homogeneous coordinate

                cv2.circle(image, (x, y), 5, (0, 0, 255), -1)
                cv2.putText(image, str(idx), (x + 10, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 0, 0), 2, cv2.LINE_AA)

        cv2_imshow(image)
    else:
        print("Landmarks pts NOT found.")

    pose.close()
    return np.array(landmarks_list)  # Return landmark points

# Load the image
image = cv2.imread('/content/A_with_person.jpg')
Q1 = VirtualCoorMediaPipe(image)

if Q1 is not None:
    # Transformation parameters for poster A
    R1 = np.array([[1.0, 0.0, 0.0],
                   [0.0, 0.00966169, -0.99995332],
                   [0.0, -0.99995332, -0.00966169]])
    T1 = np.array([[0.0], [309.86320746], [270.60082593]])
    scale_factor_A = 0.083

    def calculate_physical_coordinates(R, T, Q, scale_factor):
        R_inv = np.linalg.inv(R)
        Q_scaled = Q * scale_factor
        Q_translated = Q_scaled.T - T
        P = (R_inv @ Q_translated).T
        return P

    P1 = calculate_physical_coordinates(R1, T1, Q1, scale_factor_A)
    print("Physical Coordinates:")
    print(P1)


Output hidden; open in https://colab.research.google.com to view.

In [ ]:
import cv2
import mediapipe as mp
import numpy as np
from google.colab.patches import cv2_imshow

def VirtualCoorMediaPipe(image):
    mp_pose = mp.solutions.pose
    pose = mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5)

    excluded_points = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 13, 14, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
    landmarks_list = []

    if image is None:
        print("Error: Image not found or cannot be loaded.")
        return None

    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    result = pose.process(image_rgb)

    if result.pose_landmarks:
        for idx, landmark in enumerate(result.pose_landmarks.landmark):
            x = int(landmark.x * image.shape[1])
            y = int(landmark.y * image.shape[0])
            if idx not in excluded_points:
                print(f"point {idx}: coordinates ({x:.1f}, {y:.1f})")
                landmarks_list.append((0, x, y))  # Convert to required format

                cv2.circle(image, (x, y), 5, (0, 0, 255), -1)
                cv2.putText(image, str(idx), (x + 10, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 0, 0), 2, cv2.LINE_AA)

        cv2_imshow(image)
    else:
        print("Landmarks pts NOT found.")

    pose.close()
    return np.array(landmarks_list)  # Return landmark points in required format

# Load the image
image = cv2.imread('/content/A_with_person.jpg')
Q1 = VirtualCoorMediaPipe(image)

if Q1 is not None:
    # Transformation parameters for poster A
    R1 = np.array([[1.0, 0.0, 0.0],
                   [0.0, 0.00966169, -0.99995332],
                   [0.0, -0.99995332, -0.00966169]])
    T1 = np.array([[0.0], [309.86320746], [270.60082593]])
    scale_factor_A = 0.083

    def calculate_physical_coordinates(R, T, Q, scale_factor):
        R_inv = np.linalg.inv(R)
        Q_scaled = Q * scale_factor
        Q_translated = Q_scaled.T - T
        P = (R_inv @ Q_translated).T
        return P

    P1 = calculate_physical_coordinates(R1, T1, Q1, scale_factor_A)
    print("Physical Coordinates:")
    print(P1)


Output hidden; open in https://colab.research.google.com to view.

In [ ]:
import cv2
import mediapipe as mp
import numpy as np
from google.colab.patches import cv2_imshow

def VirtualCoorMediaPipe(image):
    mp_pose = mp.solutions.pose
    pose = mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5)

    excluded_points = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 13, 14, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
    landmarks_list = []

    if image is None:
        print("Error: Image not found or cannot be loaded.")
        return None

    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    result = pose.process(image_rgb)

    if result.pose_landmarks:
        for idx, landmark in enumerate(result.pose_landmarks.landmark):
            x = int(landmark.x * image.shape[1])
            y = int(landmark.y * image.shape[0])
            if idx not in excluded_points:
                print(f"point {idx}: coordinates ({x:.1f}, {y:.1f})")
                landmarks_list.append((x, y, 0))  # Convert to required format

                cv2.circle(image, (x, y), 5, (0, 0, 255), -1)
                cv2.putText(image, str(idx), (x + 10, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 0, 0), 2, cv2.LINE_AA)

        cv2_imshow(image)
    else:
        print("Landmarks pts NOT found.")

    pose.close()
    return np.array(landmarks_list)  # Return landmark points in required format

# Load the image
image = cv2.imread('/content/B_with_person.jpg')
Q2 = VirtualCoorMediaPipe(image)

if Q2 is not None:
    # Transformation parameters for poster B
    R2 = np.array([[0.99901468, 0.04438102, 0.0],
                   [0.04438102, -0.99901468, 0.0],
                   [0.0, 0.0, 1.0]])
    T2 = np.array([[44.62353032], [312.68703378], [0.0]])
    scale_factor_B = 0.0923

    def calculate_physical_coordinates(R, T, Q, scale_factor):
        R_inv = np.linalg.inv(R)
        Q_scaled = Q * scale_factor
        Q_translated = Q_scaled.T - T
        P = (R_inv @ Q_translated).T
        return P

    P2 = calculate_physical_coordinates(R2, T2, Q2, scale_factor_B)
    print("Physical Coordinates:")
    print(P2)


Output hidden; open in https://colab.research.google.com to view.

In [ ]:
# P1 = calculate_physical_coordinates(R1, T1, Q1, scale_factor_A)
# P2 = calculate_physical_coordinates(R2, T2, Q2, scale_factor_B)

# Fusion: Take X from poster B, Y and Z from poster A
fused_coordinates = np.column_stack((P2[:, 0], P1[:, 1], P1[:, 2]))


print("Fused 3D Coordinates:\n", fused_coordinates)

Fused 3D Coordinates:
 [[ 54.11914577 234.97256144 132.1956104 ]
 [ 83.13558944 204.65292078 108.82758061]
 [ 28.79578181 203.5266526  130.8957291 ]
 [ 86.36135703 124.96821145 134.70189946]
 [ 28.73479437 133.34359769 152.71166054]]


In [2]:
import cv2
import mediapipe as mp
import numpy as np

def VirtualCoorMediaPipe(image, order='A'):
    """
    Extracts pose landmarks from an image using MediaPipe and formats them.

    Parameters:
        image: Input image.
        order:
          'A' -> returns coordinates as (0, x, y)
          'B' -> returns coordinates as (x, y, 0)

    Returns:
        An (N, 3) NumPy array of landmarks in the specified format.
    """
    mp_pose = mp.solutions.pose
    pose = mp_pose.Pose(min_detection_confidence=0.5,
                        min_tracking_confidence=0.5)

    # Exclude specific landmark indices (as provided earlier)
    excluded_points = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                       13, 14, 17, 18, 19, 20, 21, 22, 23,
                       24, 25, 26, 27, 28, 29, 30, 31, 32]
    landmarks_list = []

    if image is None:
        print("Error: Image not found or cannot be loaded.")
        return None

    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    result = pose.process(image_rgb)

    if result.pose_landmarks:
        for idx, landmark in enumerate(result.pose_landmarks.landmark):
            # Compute pixel coordinates
            x = int(landmark.x * image.shape[1])
            y = int(landmark.y * image.shape[0])
            if idx not in excluded_points:
                if order == 'A':
                    # Format for poster A: (0, x, y)
                    landmarks_list.append((0, x, y))
                elif order == 'B':
                    # Format for poster B: (x, y, 0)
                    landmarks_list.append((x, y, 0))
                else:
                    landmarks_list.append((x, y, 0))  # default
    else:
        print("Landmarks not found.")

    pose.close()
    return np.array(landmarks_list)

# Load images (make sure the image paths are correct)
image_A = cv2.imread('/content/A_with_person.jpg')
image_B = cv2.imread('/content/B_with_person.jpg')

# Extract virtual coordinates in required formats
Q1 = VirtualCoorMediaPipe(image_A, order='A')  # For poster A: (0, x, y)
Q2 = VirtualCoorMediaPipe(image_B, order='B')  # For poster B: (x, y, 0)

if Q1 is not None and Q2 is not None:
    # Transformation parameters for poster A
    R1 = np.array([[1.0, 0.0, 0.0],
                   [0.0, 0.00966169, -0.99995332],
                   [0.0, -0.99995332, -0.00966169]])
    T1 = np.array([[0.0],
                   [309.86320746],
                   [270.60082593]])
    scale_factor_A = 0.083

    # Transformation parameters for poster B
    R2 = np.array([[0.99901468, 0.04438102, 0.0],
                   [0.04438102, -0.99901468, 0.0],
                   [0.0, 0.0, 1.0]])
    T2 = np.array([[44.62353032],
                   [312.68703378],
                   [0.0]])
    scale_factor_B = 0.0923

    def calculate_physical_coordinates(R, T, Q, scale_factor):
        """
        Converts virtual coordinates Q (shape: [N, 3]) into physical coordinates.

        The conversion applies scaling, translation, and rotation.
        """
        R_inv = np.linalg.inv(R)
        Q_scaled = Q * scale_factor  # Scale each coordinate
        Q_translated = Q_scaled.T - T  # Subtract translation vector (broadcasted)
        P = (R_inv @ Q_translated).T  # Apply rotation and transpose back
        return P

    # Calculate physical coordinates for each poster
    P1 = calculate_physical_coordinates(R1, T1, Q1, scale_factor_A)
    P2 = calculate_physical_coordinates(R2, T2, Q2, scale_factor_B)

    # Fusion: Take X from poster B, Y and Z from poster A
    fused_coordinates = np.column_stack((P2[:, 0], P1[:, 1], P1[:, 2]))

    print("Fused 3D Coordinates(normal):")
    print(fused_coordinates)

    print("===============")

    fused_coordinates2 = np.column_stack((P2[:, 0], (P1[:, 1] + P2[:, 1])/2 , P1[:, 2]))
    print("Fused 3D Coordinates(Mean):")
    print(fused_coordinates2)



Fused 3D Coordinates(normal):
[[ 54.11914577 234.97256144 132.1956104 ]
 [ 83.13558944 204.65292078 108.82758061]
 [ 28.79578181 203.5266526  130.8957291 ]
 [ 86.36135703 124.96821145 134.70189946]
 [ 28.73479437 133.34359769 152.71166054]]
Fused 3D Coordinates(Mean):
[[ 54.11914577 251.39542241 132.1956104 ]
 [ 83.13558944 218.49431092 108.82758061]
 [ 28.79578181 217.0475281  130.8957291 ]
 [ 86.36135703 139.22644093 134.70189946]
 [ 28.73479437 142.08791448 152.71166054]]


In [ ]:
import cv2
import mediapipe as mp
import numpy as np

class PoseFusion:
    def __init__(self, image_A, image_B):
        self.image_A = image_A
        self.image_B = image_B
        self.mp_pose = mp.solutions.pose
        self.excluded_points = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                                13, 14, 17, 18, 19, 20, 21, 22, 23,
                                24, 25, 26, 27, 28, 29, 30, 31, 32]

    def extract_landmarks(self, image, order='A'):
        """ Extracts and formats pose landmarks from an image using MediaPipe. """
        pose = self.mp_pose.Pose(min_detection_confidence=0.5,
                                 min_tracking_confidence=0.5)

        if image is None:
            print("Error: Image not found or cannot be loaded.")
            return None

        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        result = pose.process(image_rgb)
        landmarks_list = []

        if result.pose_landmarks:
            for idx, landmark in enumerate(result.pose_landmarks.landmark):
                x = int(landmark.x * image.shape[1])
                y = int(landmark.y * image.shape[0])
                if idx not in self.excluded_points:
                    if order == 'A':
                        landmarks_list.append((0, x, y))  # (0, x, y)
                    elif order == 'B':
                        landmarks_list.append((x, y, 0))  # (x, y, 0)
                    else:
                        landmarks_list.append((x, y, 0))  # Default
        else:
            print("Landmarks not found.")

        pose.close()
        return np.array(landmarks_list)

    def calculate_physical_coordinates(self, R, T, Q, scale_factor):
        """ Converts virtual coordinates to physical coordinates using scaling, rotation, and translation. """
        R_inv = np.linalg.inv(R)
        Q_scaled = Q * scale_factor
        Q_translated = Q_scaled.T - T  # Broadcast subtraction
        return (R_inv @ Q_translated).T

    def fuse_coordinates(self):
        """ Processes images, extracts landmarks, and fuses 3D coordinates. """
        Q1 = self.extract_landmarks(self.image_A, order='A')  # (0, x, y)
        Q2 = self.extract_landmarks(self.image_B, order='B')  # (x, y, 0)

        if Q1 is None or Q2 is None:
            return None

        # Transformation parameters for poster A
        R1 = np.array([[1.0, 0.0, 0.0],
                       [0.0, 0.00966169, -0.99995332],
                       [0.0, -0.99995332, -0.00966169]])
        T1 = np.array([[0.0],
                       [309.86320746],
                       [270.60082593]])
        scale_factor_A = 0.083

        # Transformation parameters for poster B
        R2 = np.array([[0.99901468, 0.04438102, 0.0],
                       [0.04438102, -0.99901468, 0.0],
                       [0.0, 0.0, 1.0]])
        T2 = np.array([[44.62353032],
                       [312.68703378],
                       [0.0]])
        scale_factor_B = 0.0923

        # Compute physical coordinates
        P1 = self.calculate_physical_coordinates(R1, T1, Q1, scale_factor_A)
        P2 = self.calculate_physical_coordinates(R2, T2, Q2, scale_factor_B)

        # Fusion: X from B, Y and Z from A
        fused_coordinates = np.column_stack((P2[:, 0], P1[:, 1], P1[:, 2]))
        fused_coordinates_mean = np.column_stack((P2[:, 0], (P1[:, 1] + P2[:, 1]) / 2, P1[:, 2]))

        return fused_coordinates, fused_coordinates_mean




In [ ]:
# Usage Example
image_A = cv2.imread('/content/A_with_person.jpg')
image_B = cv2.imread('/content/B_with_person.jpg')

pose_fusion = PoseFusion(image_A, image_B)
fused_coords, fused_coords_mean = pose_fusion.fuse_coordinates()

if fused_coords is not None:
    print("Fused 3D Coordinates (Normal):\n", fused_coords)
    print("===============")
    print("Fused 3D Coordinates (Mean):\n", fused_coords_mean)

Fused 3D Coordinates (Normal):
 [[ 54.11914577 234.97256144 132.1956104 ]
 [ 83.13558944 204.65292078 108.82758061]
 [ 28.79578181 203.5266526  130.8957291 ]
 [ 86.36135703 124.96821145 134.70189946]
 [ 28.73479437 133.34359769 152.71166054]]
Fused 3D Coordinates (Mean):
 [[ 54.11914577 251.39542241 132.1956104 ]
 [ 83.13558944 218.49431092 108.82758061]
 [ 28.79578181 217.0475281  130.8957291 ]
 [ 86.36135703 139.22644093 134.70189946]
 [ 28.73479437 142.08791448 152.71166054]]


# Orientation 1

In [ ]:
# Usage Example
image_A = cv2.imread('/content/o1pa1.jpg')
image_B = cv2.imread('/content/o1pb1.jpg')

pose_fusion = PoseFusion(image_A, image_B)
fused_coords, fused_coords_mean = pose_fusion.fuse_coordinates()

if fused_coords is not None:
    print("Fused 3D Coordinates (Normal):\n", fused_coords)
    print("===============")
    print("Fused 3D Coordinates (Mean):\n", fused_coords_mean)

Fused 3D Coordinates (Normal):
 [[-42.51119456 152.71333689 261.30187395]
 [-29.68016565 137.36827822 251.60816225]
 [-56.71990785 138.17699121 245.2246778 ]
 [-30.20138292  81.96415248 255.80406063]
 [-59.67133149  89.09500565 247.98759185]]
Fused 3D Coordinates (Mean):
 [[-42.51119456 224.70360945 261.30187395]
 [-29.68016565 207.79981144 251.60816225]
 [-56.71990785 208.89702496 245.2246778 ]
 [-30.20138292 161.00742242 255.80406063]
 [-59.67133149 165.58128945 247.98759185]]


In [ ]:
# Usage Example
image_A = cv2.imread('/content/o1pa2.jpg')
image_B = cv2.imread('/content/o1pb2.jpg')

pose_fusion = PoseFusion(image_A, image_B)
fused_coords, fused_coords_mean = pose_fusion.fuse_coordinates()

if fused_coords is not None:
    print("Fused 3D Coordinates (Normal):\n", fused_coords)
    print("===============")
    print("Fused 3D Coordinates (Mean):\n", fused_coords_mean)

Fused 3D Coordinates (Normal):
 [[  7.70779866 161.60433688 294.67233377]
 [ 14.60066231 136.65498324 282.47871165]
 [ -4.19151036 138.77198984 269.55056203]
 [ 13.86041166  58.26734587 285.7885091 ]
 [ -6.85795101  73.81008051 266.43277466]]
Fused 3D Coordinates (Mean):
 [[  7.70779866 227.53905811 294.67233377]
 [ 14.60066231 208.19576967 282.47871165]
 [ -4.19151036 209.66837309 269.55056203]
 [ 13.86041166 155.49641717 285.7885091 ]
 [ -6.85795101 162.48421138 266.43277466]]


In [ ]:
# Usage Example
image_A = cv2.imread('/content/o1pa3.jpg')
image_B = cv2.imread('/content/o1pb3.jpg')

pose_fusion = PoseFusion(image_A, image_B)
fused_coords, fused_coords_mean = pose_fusion.fuse_coordinates()

if fused_coords is not None:
    print("Fused 3D Coordinates (Normal):\n", fused_coords)
    print("===============")
    print("Fused 3D Coordinates (Mean):\n", fused_coords_mean)

Fused 3D Coordinates (Normal):
 [[-19.53098434 157.0451896  208.13824529]
 [ -9.80622562 139.08755858 193.93708132]
 [-29.00209441 138.69583363 191.52618405]
 [ -7.37450111  77.87691168 197.74486077]
 [-29.74033765  83.6509577  192.90342181]]
Fused 3D Coordinates (Mean):
 [[-19.53098434 218.83381063 208.13824529]
 [ -9.80622562 204.38895668 193.93708132]
 [-29.00209441 203.95149003 191.52618405]
 [ -7.37450111 159.93279693 197.74486077]
 [-29.74033765 161.86106594 192.90342181]]


In [ ]:
# Usage Example
image_A = cv2.imread('/content/o1pa4.jpg')
image_B = cv2.imread('/content/o1pb4.jpg')

pose_fusion = PoseFusion(image_A, image_B)
fused_coords, fused_coords_mean = pose_fusion.fuse_coordinates()

if fused_coords is not None:
    print("Fused 3D Coordinates (Normal):\n", fused_coords)
    print("===============")
    print("Fused 3D Coordinates (Mean):\n", fused_coords_mean)

Fused 3D Coordinates (Normal):
 [[-37.88468254 159.23277042 170.72463455]
 [-29.44265785 140.33170904 159.66850226]
 [-46.91932555 140.50652242 158.75714871]
 [-28.27720034  89.24578764 163.65711211]
 [-48.19845247  93.33424968 161.45551079]]
Fused 3D Coordinates (Mean):
 [[-37.88468254 219.56611694 170.72463455]
 [-29.44265785 204.52866418 159.66850226]
 [-46.91932555 204.78221841 158.75714871]
 [-28.27720034 166.90836553 163.65711211]
 [-48.19845247 168.55629332 161.45551079]]


In [ ]:
# Usage Example
image_A = cv2.imread('/content/o1pa5.jpg')
image_B = cv2.imread('/content/o1pb5.jpg')

pose_fusion = PoseFusion(image_A, image_B)
fused_coords, fused_coords_mean = pose_fusion.fuse_coordinates()

if fused_coords is not None:
    print("Fused 3D Coordinates (Normal):\n", fused_coords)
    print("===============")
    print("Fused 3D Coordinates (Mean):\n", fused_coords_mean)

Fused 3D Coordinates (Normal):
 [[  8.59060676 168.25649609 164.58653247]
 [ 14.11270525 142.72176163 144.2528746 ]
 [ -0.86612525 142.56418691 151.97071243]
 [ 14.34587206  65.36014716 153.05084135]
 [ -2.11448864  75.21102475 155.80214591]]
Fused 3D Coordinates (Mean):
 [[  8.59060676 221.96901214 164.58653247]
 [ 14.11270525 204.24279704 144.2528746 ]
 [ -0.86612525 204.29324914 151.97071243]
 [ 14.34587206 154.61883138 153.05084135]
 [ -2.11448864 158.67049543 155.80214591]]


# Orientation 2

In [ ]:
# Usage Example
image_A = cv2.imread('/content/o2pa1.jpg')
image_B = cv2.imread('/content/o2pb1.jpg')

pose_fusion = PoseFusion(image_A, image_B)
fused_coords, fused_coords_mean = pose_fusion.fuse_coordinates()

if fused_coords is not None:
    print("Fused 3D Coordinates (Normal):\n", fused_coords)
    print("===============")
    print("Fused 3D Coordinates (Mean):\n", fused_coords_mean)

Fused 3D Coordinates (Normal):
 [[  3.53524961 161.29080703 258.39661119]
 [ 48.22690637 144.14148543 246.44436183]
 [-43.97596274 144.69238892 240.97142901]
 [ 55.56030228  84.01299585 249.93058174]
 [-48.26717455  93.82298075 239.73288675]]
Fused 3D Coordinates (Mean):
 [[  3.53524961 211.9526991  258.39661119]
 [ 48.22690637 177.66973805 246.44436183]
 [-43.97596274 176.867249   240.97142901]
 [ 55.56030228  87.94519057 249.93058174]
 [-48.26717455  88.46512768 239.73288675]]


In [ ]:
# Usage Example
image_A = cv2.imread('/content/o2pa2.jpg')
image_B = cv2.imread('/content/o2pb2.jpg')

pose_fusion = PoseFusion(image_A, image_B)
fused_coords, fused_coords_mean = pose_fusion.fuse_coordinates()

if fused_coords is not None:
    print("Fused 3D Coordinates (Normal):\n", fused_coords)
    print("===============")
    print("Fused 3D Coordinates (Mean):\n", fused_coords_mean)

Fused 3D Coordinates (Normal):
 [[207.81669064 175.2144961  303.51924388]
 [222.61639137 144.2709772  293.17679441]
 [157.55575521 146.8615046  274.19393716]
 [219.59402479  54.44511087 294.79900046]
 [148.18100094  72.11166581 270.40055032]]
Fused 3D Coordinates (Mean):
 [[207.81669064 209.50107772 303.51924388]
 [222.61639137 171.99942468 293.17679441]
 [157.55575521 172.45007748 274.19393716]
 [219.59402479  75.83472427 294.79900046]
 [148.18100094  78.36980458 270.40055032]]


In [ ]:
# Usage Example
image_A = cv2.imread('/content/o2pa3.jpg')
image_B = cv2.imread('/content/o2pb3.jpg')

pose_fusion = PoseFusion(image_A, image_B)
fused_coords, fused_coords_mean = pose_fusion.fuse_coordinates()

if fused_coords is not None:
    print("Fused 3D Coordinates (Normal):\n", fused_coords)
    print("===============")
    print("Fused 3D Coordinates (Mean):\n", fused_coords_mean)

Fused 3D Coordinates (Normal):
 [[ 81.43293691 170.17381405 206.68802229]
 [102.66285634 144.91492967 192.16730096]
 [ 48.82505766 145.60536205 189.43484415]
 [105.27392407  73.14132096 198.19712807]
 [ 47.02840212  81.09572002 191.0526475 ]]
Fused 3D Coordinates (Mean):
 [[ 81.43293691 204.82018791 206.68802229]
 [102.66285634 174.73845237 192.16730096]
 [ 48.82505766 173.74921548 189.43484415]
 [105.27392407 100.10541149 198.19712807]
 [ 47.02840212  99.32417461 191.0526475 ]]


In [ ]:
# Usage Example
image_A = cv2.imread('/content/o2pa4.jpg')
image_B = cv2.imread('/content/o2pb4.jpg')

pose_fusion = PoseFusion(image_A, image_B)
fused_coords, fused_coords_mean = pose_fusion.fuse_coordinates()

if fused_coords is not None:
    print("Fused 3D Coordinates (Normal):\n", fused_coords)
    print("===============")
    print("Fused 3D Coordinates (Mean):\n", fused_coords_mean)

Fused 3D Coordinates (Normal):
 [[  3.99580562 168.07887861 157.19747146]
 [ 28.25842369 146.79097758 144.04318032]
 [-24.76170106 147.43489858 146.12449884]
 [ 31.94130327  88.96472769 149.79274941]
 [-28.12775485  95.86142538 149.02934752]]
Fused 3D Coordinates (Mean):
 [[  3.99580562 202.88417526 157.19747146]
 [ 28.25842369 176.01018282 144.04318032]
 [-24.76170106 177.23323758 146.12449884]
 [ 31.94130327 111.88548819 149.79274941]
 [-28.12775485 114.46151449 149.02934752]]


In [ ]:
# Usage Example
image_A = cv2.imread('/content/o2pa5.jpg')
image_B = cv2.imread('/content/o2pb5.jpg')

pose_fusion = PoseFusion(image_A, image_B)
fused_coords, fused_coords_mean = pose_fusion.fuse_coordinates()

if fused_coords is not None:
    print("Fused 3D Coordinates (Normal):\n", fused_coords)
    print("===============")
    print("Fused 3D Coordinates (Mean):\n", fused_coords_mean)

Fused 3D Coordinates (Normal):
 [[124.90203165 180.83542779 142.7120451 ]
 [139.57707856 145.79543289 118.21935622]
 [ 97.02774078 146.9766195  133.42047806]
 [141.85031823  55.76387664 132.53916768]
 [ 93.90771371  67.4988056  137.88179632]]
Fused 3D Coordinates (Mean):
 [[124.90203165 203.40189614 142.7120451 ]
 [139.57707856 172.53399351 118.21935622]
 [ 97.02774078 172.64141923 133.42047806]
 [141.85031823  95.6938025  132.53916768]
 [ 93.90771371  99.38765443 137.88179632]]
