## Virtual coordinates

In [ ]:
# For poster A
# virtual coordinates
'''
Point 1: (1072, 1375)
Point 2: (1410, 1379)
Point 3: (1754, 1382)
Point 4: (1245, 1463)
Point 5: (1582, 1468)
Point 6: (1075, 1632)
Point 7: (1245, 1635)
Point 8: (1411, 1639)
Point 9: (1578, 1640)
Point 10: (1748, 1642)
Point 11: (1244, 1802)
Point 12: (1578, 1807)
Point 13: (1075, 1886)
Point 14: (1414, 1886)
Point 15: (1742, 1894)

'''



## physical coordinates

In [ ]:
'''(0,154,222)
(0,154,194)
(0,154,166)
(0,147,208)
(0,147,180)
(0,133,222)
(0,133,208)
(0,133,194)
(0,133,180)
(0,133,166)
(0,119,208)
(0,119,180)
(0,112,222)
(0,112,194)
(0,112,166)
'''

'\nPhysical points\n'

In [ ]:
import traceback
import numpy as np
import json

try:
    # Define virtual coordinates in pixels (Q)
    Q = np.array([
        (0, 1072, 1375),
        (0, 1410, 1379),
        (0, 1754, 1382),
        (0, 1245, 1463),
        (0, 1582, 1468),
        (0, 1075, 1632),
        (0, 1245, 1635),
        (0, 1411, 1639),
        (0, 1578, 1640),
        (0, 1748, 1642),
        (0, 1244, 1802),
        (0, 1578, 1807),
        (0, 1075, 1886),
        (0, 1414, 1886),
        (0, 1742, 1894)
    ]).T

    # Convert virtual coordinates from pixels to cm
    Q = Q * 0.083

    # Define physical coordinates (P)
    P = np.array([
        (0, 154, 222),
        (0, 154, 194),
        (0, 154, 166),
        (0, 147, 208),
        (0, 147, 180),
        (0, 133, 222),
        (0, 133, 208),
        (0, 133, 194),
        (0, 133, 180),
        (0, 133, 166),
        (0, 119, 208),
        (0, 119, 180),
        (0, 112, 222),
        (0, 112, 194),
        (0, 112, 166)
    ]).T

    # Compute the mean of P and Q
    P_bar = np.mean(P, axis=1).reshape(-1, 1)
    Q_bar = np.mean(Q, axis=1).reshape(-1, 1)

    # Compute the covariance matrix
    P_cov = P - P_bar
    Q_cov = Q - Q_bar
    cov_mat = np.matmul(P_cov, Q_cov.T)

    # Perform SVD on the covariance matrix
    u, s, v = np.linalg.svd(cov_mat)

    # Compute the rotation matrix
    R = np.matmul(v.T, u.T)

    # Compute the translation vector
    T = Q_bar - np.matmul(R, P_bar)

    # Compute the error
    err = Q - (np.matmul(R, P) + np.array([T] * P.shape[1]).T)

    # Compute the inverse of the rotation matrix
    R_inv = np.linalg.inv(R)

    # Print the results as JSON
    print(json.dumps({
        "R": R.tolist(),
        "T": T.tolist(),
        "P": P.tolist(),
        "err": err.tolist(),
        "R_inv": R_inv.tolist()
    }))

except Exception as e:
    traceback.print_exc()


{"R": [[1.0, 0.0, 0.0], [0.0, 0.009661685908716229, -0.9999533248234148], [0.0, -0.999953324823415, -0.009661685908716112]], "T": [[0.0], [309.86320745654984], [270.6008259344718]], "P": [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [154, 154, 154, 147, 147, 133, 133, 133, 133, 133, 119, 119, 112, 112, 112], [222, 194, 166, 208, 180, 222, 208, 194, 180, 166, 208, 180, 222, 194, 166]], "err": [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [-0.38546897569406724, -0.3301620707496795, 0.22314483419469866, 0.041816278139151564, 0.01412318308354088, 0.06642642838899349, 0.17707988086118576, -0.04426666666662982, -0.18261321419441856, -0.0719597617222405, 0.22934348358322154, -0.04734961147238437, 0.2693218324720448, 0.4076287374164309, -0.36706435763917966], [-0.338119639930909, -0.27664684537496953, -0.29817405081901427, -0.16905651641684472, -0.024583721860878427, -0.006139461222602449, 0.10759693605535858, 0.304333333333318, 0.25206973061131066, 0.2828061

In [ ]:
## to calculating scaling factor

import numpy as np

# Define the coordinates
virtual_point_1 = np.array([0, 1072, 1375])
virtual_point_2 = np.array([0, 1410, 1379])

physical_point_1 = np.array([0,154,222])
physical_point_2 = np.array([0,154,194])

# Calculate Euclidean distance in virtual coordinates (pixels)
virtual_distance = np.linalg.norm(virtual_point_2 - virtual_point_1)

# Calculate Euclidean distance in physical coordinates (cm)
physical_distance = np.linalg.norm(physical_point_2 - physical_point_1)

# Calculate the scaling factor
scaling_factor = physical_distance / virtual_distance

virtual_distance, physical_distance, scaling_factor


(338.02366781040644, 28.0, 0.08283443636173096)

In [ ]:
## scaling factor = 0.083 cm/pixels

In [ ]:
R

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.00966169, -0.99995332],
       [ 0.        , -0.99995332, -0.00966169]])

In [ ]:
T

array([[  0.        ],
       [309.86320746],
       [270.60082593]])

# Calculated R and T for poster A

In [ ]:
import cv2
from google.colab.patches import cv2_imshow

# Define the points
virtual_points = [
    (0, 1072, 1375),
    (0, 1410, 1379),
    (0, 1754, 1382),
    (0, 1245, 1463),
    (0, 1582, 1468),
    (0, 1075, 1632),
    (0, 1245, 1635),
    (0, 1411, 1639),
    (0, 1578, 1640),
    (0, 1748, 1642),
    (0, 1244, 1802),
    (0, 1578, 1807),
    (0, 1075, 1886),
    (0, 1414, 1886),
    (0, 1742, 1894)
]

# Load image (Ensure that the path is correct)
img = cv2.imread('/content/IMG-A2.jpg')

# Check if the image is loaded properly
if img is None:
    print("Error: Image not loaded. Check the file path.")
else:
    # Draw red circles at the given virtual points
    for point in virtual_points:
        center = (point[1], point[2])  # Use (x, y) coordinates only
        cv2.circle(img, center, 3, (0, 0, 255), -1)  # Red color in BGR

    # Display the image in Google Colab
    cv2_imshow(img)


Output hidden; open in https://colab.research.google.com to view.

In [ ]:
import numpy as np

def coo(R, P, T):
    # Perform the transformation: Q_hat = (R @ P) + T
    Q_hat = (R @ P) + T

    # Scale by the factor 0.083
    Q_hat /= 0.083

    # Extract the coordinates from Q_hat
    m_x, m_y, m_z = Q_hat

    # Construct the desired output format with (z, x, y) as tuples
    result = np.array([(int(x), int(y), int(z)) for x, y, z in zip(m_x, m_y, m_z)])

    return result
coo(R, P,T)


array([[   0, 1076, 1379],
       [   0, 1413, 1382],
       [   0, 1751, 1385],
       [   0, 1244, 1465],
       [   0, 1581, 1468],
       [   0, 1074, 1632],
       [   0, 1242, 1633],
       [   0, 1411, 1635],
       [   0, 1580, 1636],
       [   0, 1748, 1638],
       [   0, 1241, 1802],
       [   0, 1578, 1805],
       [   0, 1071, 1885],
       [   0, 1409, 1888],
       [   0, 1746, 1891]])

In [ ]:
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Define the points
# Virtual points
virtual_points = np.array([
    (0, 1072, 1375),
    (0, 1410, 1379),
    (0, 1754, 1382),
    (0, 1245, 1463),
    (0, 1582, 1468),
    (0, 1075, 1632),
    (0, 1245, 1635),
    (0, 1411, 1639),
    (0, 1578, 1640),
    (0, 1748, 1642),
    (0, 1244, 1802),
    (0, 1578, 1807),
    (0, 1075, 1886),
    (0, 1414, 1886),
    (0, 1742, 1894)
])

# Physical points
phy_points = np.array([
    [0, 1076, 1379],
    [0, 1413, 1382],
    [0, 1751, 1385],
    [0, 1244, 1465],
    [0, 1581, 1468],
    [0, 1074, 1632],
    [0, 1242, 1633],
    [0, 1411, 1635],
    [0, 1580, 1636],
    [0, 1748, 1638],
    [0, 1241, 1802],
    [0, 1578, 1805],
    [0, 1071, 1885],
    [0, 1409, 1888],
    [0, 1746, 1891]
])

# Load image (Ensure that the path is correct)
img = cv2.imread('/content/IMG-A2.jpg')

# Check if the image is loaded properly
if img is None:
    print("Error: Image not loaded. Check the file path.")
else:
    # Draw red circles at the given virtual points
    for point in virtual_points:
        center = (point[1], point[2])  # Use (x, y) coordinates only
        cv2.circle(img, center, 3, (0, 0, 255), -1)  # Red color in BGR

    # Draw blue circles at the given physical points
    for p in phy_points:
        center = (p[1], p[2])  # Use (x, y) coordinates only
        cv2.circle(img, center, 3, (255, 0, 0), -1)  # Blue color in BGR

    # Display the image in Google Colab
    cv2_imshow(img)


Output hidden; open in https://colab.research.google.com to view.

In [ ]:

# Virtual points
Q = np.array([
    (0, 1072, 1375),
    (0, 1410, 1379),
    (0, 1754, 1382),
    (0, 1245, 1463),
    (0, 1582, 1468),
    (0, 1075, 1632),
    (0, 1245, 1635),
    (0, 1411, 1639),
    (0, 1578, 1640),
    (0, 1748, 1642),
    (0, 1244, 1802),
    (0, 1578, 1807),
    (0, 1075, 1886),
    (0, 1414, 1886),
    (0, 1742, 1894)
])
Q = Q * 0.083
Q = np.array(Q)

# Inverse the rotation matrix
R_inv = np.linalg.inv(R)

Q_translated = Q.T - T

# Apply the inverse rotation
P = (R_inv @ Q_translated).T
print("The physical coordinates in (cm):")
print(P)


The physical coordinates in (cm):
[[  0.         154.33437958 222.38871779]
 [  0.         154.27344401 194.33281954]
 [  0.         154.30031609 165.77974645]
 [  0.         147.16945264 207.95981904]
 [  0.         147.02471903 179.986115  ]
 [  0.         133.00678097 221.93363599]
 [  0.         132.89411898 207.82188882]
 [  0.         132.69525318 194.04132423]
 [  0.         132.74617768 180.18016927]
 [  0.         132.71651182 166.06922402]
 [  0.         119.03296402 207.77096431]
 [  0.         118.88582465 180.04624864]
 [  0.         111.92576497 221.72994833]
 [  0.         112.19761583 193.59426163]
 [  0.         111.79667656 166.36511695]]


In [ ]:
import numpy as np

# Actual physical coordinates
P = np.array([
    (0, 154, 222),
    (0, 154, 194),
    (0, 154, 166),
    (0, 147, 208),
    (0, 147, 180),
    (0, 133, 222),
    (0, 133, 208),
    (0, 133, 194),
    (0, 133, 180),
    (0, 133, 166),
    (0, 119, 208),
    (0, 119, 180),
    (0, 112, 222),
    (0, 112, 194),
    (0, 112, 166)
])

# Predicted points
P_hat = np.array([
    [0.0, 154.33437958, 222.38871779],
    [0.0, 154.27344401, 194.33281954],
    [0.0, 154.30031609, 165.77974645],
    [0.0, 147.16945264, 207.95981904],
    [0.0, 147.02471903, 179.986115],
    [0.0, 133.00678097, 221.93363599],
    [0.0, 132.89411898, 207.82188882],
    [0.0, 132.69525318, 194.04132423],
    [0.0, 132.74617768, 180.18016927],
    [0.0, 132.71651182, 166.06922402],
    [0.0, 119.03296402, 207.77096431],
    [0.0, 118.88582465, 180.04624864],
    [0.0, 111.92576497, 221.72994833],
    [0.0, 112.19761583, 193.59426163],
    [0.0, 111.79667656, 166.36511695]
])

# Calculate differences for Y and Z coordinates
y_diff = P[:, 1] - P_hat[:, 1]
z_diff = P[:, 2] - P_hat[:, 2]

# Compute mean differences
mean_y_diff = np.mean(y_diff)
mean_z_diff = np.mean(z_diff)

print("Mean Y Difference:", mean_y_diff)
print("Mean Z Difference:", mean_z_diff)


Mean Y Difference: -6.666643533511282e-10
Mean Z Difference: -6.666671955220712e-10


In [ ]:
y_diff

array([-0.33437958, -0.27344401, -0.30031609, -0.16945264, -0.02471903,
       -0.00678097,  0.10588102,  0.30474682,  0.25382232,  0.28348818,
       -0.03296402,  0.11417535,  0.07423503, -0.19761583,  0.20332344])