In [ ]:
import traceback
import sys
import json
import numpy as np

try:

    argv_str = sys.argv[1].replace("\"QTE\"", "\"")
    argv_json = json.loads(argv_str)


    Q = np.array([
        (28.25, 30.25, 0),
        (27.25, 39.25, 0),
        (28.25, 39.25, 0),
        (29.25, 39.25, 0),
        (28.25, 40.25, 0),
        (7.25, 38.25, 0),
        (6.75, 39.0, 0),
        (6.75, 39.25, 0),
        (7.75, 39.25, 0),
        (7.25, 40.0, 0)
    ]).T


    P = []
    for p_i in argv_json:
        P.append([p_i['x'], p_i['y'], p_i['z']])
    P = np.array(P).T

    # Convert [m] to [in]
    P = 39.37 * P


    P_bar = np.mean(P, axis=1).reshape(-1, 1)
    Q_bar = np.mean(Q, axis=1).reshape(-1, 1)

    # Compute the covariance matrix
    P_cov = P - P_bar
    Q_cov = Q - Q_bar
    cov_mat = np.matmul(P_cov, Q_cov.T)

    # Perform SVD on the covariance matrix
    u, s, v = np.linalg.svd(cov_mat)

    # Compute the rotation matrix
    R = np.matmul(v.T, u.T)

    # Compute the translation vector
    T = Q_bar - np.matmul(R, P_bar)

    # Compute the error
    err = Q - (np.matmul(R, P) + np.array([T] * P.shape[1]).T)

    # Compute the inverse of the rotation matrix
    R_inv = np.linalg.inv(R)

    # Print the results as JSON
    print(json.dumps({
        "R": R.tolist(),
        "T": T.tolist(),
        "P": P.tolist(),
        "err": err.tolist(),
        "R_inv": R_inv.tolist()
    }))

except Exception as e:
    traceback.print_exc()


Traceback (most recent call last):
  File "<ipython-input-2-7355bb4e3dc4>", line 9, in <cell line: 0>
    argv_json = json.loads(argv_str)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


In [ ]:
import traceback
import numpy as np
import json

try:
    # Define virtual coordinates in pixels (Q)
    Q = np.array([
        (1223, 1745, 0),
        (1526, 1758, 0),
        (1842, 1768, 0),
        (1370, 1828, 0),
        (1679, 1842, 0),
        (1217, 1973, 0),
        (1366, 1985, 0),
        (1518, 1992, 0),
        (1673, 1998, 0),
        (1833, 2005, 0),
        (1362, 2139, 0),
        (1666, 2163, 0),
        (1213, 2205, 0),
        (1512, 2226, 0),
        (1823, 2245, 0)
    ]).T

    ### virtual coordinates the physical coordinates(pixel to cm)
    Q = Q * 0.0923


    # Define physical coordinates (P)
    P = np.array([
        (62, 154, 0),
        (90,154 , 0),
        (118, 154, 0),
        (76, 147, 0),
        (104, 147, 0),
        (62, 133, 0),
        (76, 133, 0),
        (90, 133, 0),
        (104, 133, 0),
        (118, 133, 0),
        (76, 119, 0),
        (104, 119, 0),
        (62, 112, 0),
        (90, 112, 0),
        (118, 112, 0)
    ]).T

    # Compute the mean of P and Q
    P_bar = np.mean(P, axis=1).reshape(-1, 1)
    Q_bar = np.mean(Q, axis=1).reshape(-1, 1)

    # Compute the covariance matrix
    P_cov = P - P_bar
    Q_cov = Q - Q_bar
    cov_mat = np.matmul(P_cov, Q_cov.T)

    # Perform SVD on the covariance matrix
    u, s, v = np.linalg.svd(cov_mat)

    # Compute the rotation matrix
    R = np.matmul(v.T, u.T)

    # Compute the translation vector
    T = Q_bar - np.matmul(R, P_bar)

    # Compute the error
    err = Q - (np.matmul(R, P) + np.array([T] * P.shape[1]).T)

    # Compute the inverse of the rotation matrix
    R_inv = np.linalg.inv(R)

    # Print the results as JSON
    print(json.dumps({
        "R": R.tolist(),
        "T": T.tolist(),
        "P": P.tolist(),
        "err": err.tolist(),
        "R_inv": R_inv.tolist()
    }))

except Exception as e:
    traceback.print_exc()


{"R": [[0.9990146771882423, 0.04438101804231066, 0.0], [0.04438101804231066, -0.9990146771882422, 0.0], [0.0, 0.0, 1.0]], "T": [[44.62353032009756], [312.68703377556153], [0.0]], "P": [[62, 90, 118, 76, 104, 62, 76, 90, 104, 118, 76, 104, 62, 90, 118], [154, 154, 154, 147, 147, 133, 133, 133, 133, 133, 119, 119, 112, 112, 112], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], "err": [[[-0.5142170842844394, -0.5197280455552402, 0.6746609931739727, -0.6216554386236481, -0.07336639989443938, -0.13601570539590568, -0.36952118603130657, -0.32612666666668133, -0.005832147302101021, 0.7759623720625086, -0.11738693343895079, -0.030597894709728735, 0.426785673492617, 0.052074712221809705, 0.7849637509510217], [-0.5268966071955106, -0.5696651123801928, -0.8893336175648869, -0.480433600105556, -0.43090210529024375, -0.46180482814861534, 0.024460919259070124, 0.04922666666669784, -0.018307585925640524, 0.006458161482015612, 0.25245543862368436, 1.2249869334389416, -0.027513049101685283, 0.668118445

In [ ]:
R

array([[ 0.99901468,  0.04438102,  0.        ],
       [ 0.04438102, -0.99901468,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [ ]:
T

array([[ 44.62353032],
       [312.68703378],
       [  0.        ]])

In [ ]:
m=  (R @ P) + T
m

array([[113.39711708, 141.36952805, 169.34193901, 127.07265544,
        155.0450664 , 112.46511571, 126.45132119, 140.43752667,
        154.42373215, 168.40993763, 125.82998693, 153.80239789,
        111.53311433, 139.50552529, 167.47793625],
       [161.59039661, 162.83306511, 164.07573362, 169.2048336 ,
        170.44750211, 182.56970483, 183.19103908, 183.81237333,
        184.43370759, 185.05504184, 197.17724456, 198.41991307,
        203.54901305, 204.79168155, 206.03435006],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ]])

In [ ]:
import numpy as np
def coo(R, P, T):
  Q_hat=  (R @ P) + T
  Q_hat = Q_hat / 0.0923
  m_x, m_y, _ = Q_hat
  # return np.array(",".join(f"({i},{j})" for i, j in zip(m_x, m_y)))
  return ([(i, j) for i, j in zip(m_x, m_y)])
coo(R, P, T)

[(1228.5711493421934, 1750.708522288142),
 (1531.630856398215, 1764.17188637465),
 (1834.6905634542363, 1777.6352504611582),
 (1376.735161848577, 1833.2051310954014),
 (1679.7948689045986, 1846.6684951819095),
 (1218.4736262773122, 1978.003302580158),
 (1370.003479805323, 1984.7349846234122),
 (1521.5333333333335, 1991.4666666666662),
 (1673.0631868613443, 1998.19834870992),
 (1824.593040389355, 2004.9300307531744),
 (1363.271797762069, 2136.2648381514227),
 (1666.3315048180903, 2149.7282022379313),
 (1208.376103212431, 2205.2980828721743),
 (1511.4358102684525, 2218.7614469586824),
 (1814.4955173244741, 2232.2248110451906)]

In [ ]:
## to calculating scaling factor

import numpy as np

# Define the coordinates
virtual_point_1 = np.array([1223, 1745])
virtual_point_2 = np.array([1526, 1758])

physical_point_1 = np.array([62, 154])
physical_point_2 = np.array([90, 154])

# Calculate Euclidean distance in virtual coordinates (pixels)
virtual_distance = np.linalg.norm(virtual_point_2 - virtual_point_1)

# Calculate Euclidean distance in physical coordinates (cm)
physical_distance = np.linalg.norm(physical_point_2 - physical_point_1)

# Calculate the scaling factor
scaling_factor = physical_distance / virtual_distance

virtual_distance, physical_distance, scaling_factor


(303.27874966769434, 28.0, 0.09232430571109874)

In [ ]:
## scaling factor = 0.0923 cm/pixel